apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: moira-rocks-__CI_ENVIRONMENT_SLUG__
  labels:
    app: moira-rocks
    ref: __CI_ENVIRONMENT_SLUG__
spec:
  tls:
  - hosts:
    - __HOST__
    secretName: tls-wildcard-edenmal-net
  rules:
  - host: __HOST__
    http:
      paths:
      - path: /__PATH__
        backend:
          serviceName: moira-rocks-__CI_ENVIRONMENT_SLUG__
          servicePort: 80
