apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: moira-rocks-__CI_ENVIRONMENT_SLUG__
  labels:
    app: moira-rocks
    ref: __CI_ENVIRONMENT_SLUG__
spec:
  tls:
  - hosts:
    - dev.moira.rocks.
    # the secret used here is an unsigned wildcard cert for demo purposes
    # use your own or comment this out
    secretName: tls-wildcard-demo
  rules:
  - host: dev.moira.rocks
    http:
      paths:
      - path: /__CI_ENVIRONMENT_SLUG__
        backend:
          serviceName: moira-rocks-__CI_ENVIRONMENT_SLUG__
          servicePort: 8000
