apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: moira-rocks-__CI_ENVIRONMENT_SLUG__
  labels:
    app: moira-rocks
    ref: __CI_ENVIRONMENT_SLUG__
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - __CI_ENVIRONMENT_SLUG__-moira-rocks.edenmal.net
    # the secret used here is an unsigned wildcard cert for demo purposes
    # use your own or comment this out
    secretName: tls-wildcard-demo
  rules:
  - host: __CI_ENVIRONMENT_SLUG__-moira-rocks.edenmal.net
    http:
      paths:
      - path: /
        backend:
          serviceName: moira-rocks-__CI_ENVIRONMENT_SLUG__
          servicePort: 8000
